# ---------------------------
# USERS ROUTES
# ---------------------------

### Register User (choose role: admin or user)
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "Ekemini Tom",
  "email": "ekeminitom@gmail.com",
  "password": "Ekemini@Tom",
  "role": "admin"
}

### Login User
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "ekeminitom@gmail.com",
  "password": "Ekemini@Tom"
}

# Copy the "token" from the login response and replace {{TOKEN}} below

# ---------------------------
# BOOKINGS ROUTES
# ---------------------------

### Get All Bookings
GET http://localhost:3000/bookings

### Create Booking (requires token)
POST http://localhost:3000/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Y2RhODJlZDc2YjdkYzIzMjEyMmY1NCIsImVtYWlsIjoiZWtlbWluaXRvbUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTgzODE0OTQsImV4cCI6MTc1ODM4NTA5NH0.HEV1GVyoNAxqzy2Ps0T96L6Hzi7i5cmcCpnUS4SOF50

{
  "movie": "The Man from UNCLE",
  "theater": "Lionsgate",
  "showTime": "2025-09-20T19:00:00Z",
  "seat": "A09",
  "price": 12.00,
  "quantity": 3,
  "category": "Action"
}

### Update Booking (requires token)
PUT http://localhost:3000/bookings/68cdaa497827f03d7cdb1386
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Y2RhODJlZDc2YjdkYzIzMjEyMmY1NCIsImVtYWlsIjoiZWtlbWluaXRvbUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTgzNTcxODAsImV4cCI6MTc1ODM2MDc4MH0.ASSSoQVobgsvJkxc8v8FYa8hLnL5Squd9eEK6O0vpQg

{
  "movie": "The Conjuring - The Finale",
  "theater": "Blue Rays",
  "showTime": "2025-09-20T19:00:00Z",
  "seat": "F18",
  "price": 25.00,
  "quantity": 5,
  "category": "Horror"
}

### Delete Booking (requires token)
DELETE http://localhost:3000/bookings/68cdaa497827f03d7cdb1386
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Y2RhODJlZDc2YjdkYzIzMjEyMmY1NCIsImVtYWlsIjoiZWtlbWluaXRvbUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTgzNTcxODAsImV4cCI6MTc1ODM2MDc4MH0.ASSSoQVobgsvJkxc8v8FYa8hLnL5Squd9eEK6O0vpQg
